cash_desk = []
cash_desk.append("Tom")
cash_desk.append("Bob")
print(cash_desk)
served_costumer = cash_desk.pop(0)
print(served_costumer, " is served.")
cash_desk.append("Pam")
cash_desk.append("Jim")
print(cash_desk)
served_costumer = cash_desk.pop(0)
print(served_costumer, " is served.")
print(cash_desk)
